### ISSUE TITLE
move tutor documentation to the tutor package and make rascal-website depend on it

### ISSUE THREAD

**Issue by jurgenvinju** [usethesource/rascal-tutor#18]
* it fits better here also for maintenance
* the website is better if less-relevant information for general Rascal users is focused into the Packages section

**Comment by jurgenvinju** [comment]
there might be surprises if the tutor code is both available via the rascal-maven-plugin and via the rascal tutor dependency in the website, so look out for that.

**Comment by JJWTimmer** [comment]
Done and live: https://www.rascal-mpl.org/docs/Packages/rascal-tutor/
